### ISSUE TITLE
SysLogHandler in log_qpylib does not use an RFC 5424 compliant header

### ISSUE THREAD

**Issue by alaaalii** [IBM/qpylib#30]
In `log_qpylib` we add a `SysLogHandler` for our logger in the following lines:

https://github.com/IBM/qpylib/blob/f506c74a3b96f285bd69cb13c7c3941a8e418a1c/qpylib/log_qpylib.py#L29-L35

But we're using this formatter:
https://github.com/IBM/qpylib/blob/f506c74a3b96f285bd69cb13c7c3941a8e418a1c/qpylib/log_qpylib.py#L11

As a result, the format of the emitted records that go to QRadar through syslog is this:

```
<14>2020-07-15 15:31:43,932 <stdin>.<module>: This is a test info syslog message.
```

This is not compliant with neither the [RFC 3164](https://tools.ietf.org/html/rfc3164#section-4.1.2) and the [RFC 5424](https://tools.ietf.org/html/rfc5424#section-6.2) headers, so it'll make it harder for users to try and associate app logs to a specific log source in the future. It would be best if we have a separate formatter for the syslog handler to include a properly formatted syslog header. Though a properly formatted syslog header contains a `HOSTNAME` part that contains the host that emitted the message, like this example where the hostname is `myserver`:

```
<14>1 2020-01-01T05:10:20.841485+01:00 myserver This is a test syslog message
```

We'd need to make a decision on what to use for the `HOSTNAME` since using the actual hostname of the container will probably be useless and not persistent. Maybe we can use the app's name - it could have invalid characters though.

**Comment by mbengit** [comment]
Thanks for pointing this out. One concern is: if we change the format are we going to break anything that consumes messages with the existing format?

**Comment by alaaalii** [comment]
Most likely not. Anything that is consuming syslog messages with the existing format will be using the IP address of the container to identify the container logs. If we implement this change, they can still consume the messages using the IP address. So implementing this change will definitely put us in the right direction of properly consuming app logs.
