### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tristanlatr** [IBM/qpylib#40]
Hello,

I couldn't find any documentation or code snippet that would help me use this library.
Do you have other documentation ? 

Thanks

**Comment by jthomperoo** [comment]
Hi,

Thanks for raising this, at the moment we are looking at adding documentation to this library including documentation, examples, and an API reference similar to the one you have proposed in #41. I'll keep this issue updated with any changes we add in around documentation.

Thanks again for highlighting this.

**Comment by harsh-nasit** [comment]
HI @jthomperoo 
How do we ensure that the latest qpylib package is used inside the app container? Is it using `"image": "qradar-app-base:2.0.0"` tag in manifest.json of the app? Is the qpylib package automatically updated the app docker starts?

**Comment by jthomperoo** [comment]
Hi @harsh-nasit 
QPyLib is bundled with the qradar-app-base image, so you don't have to worry about managing the QPyLib version. New qradar-app-base image versions go out with new QRadar releases, which at the minute will mean that apps will automatically upgrade to the latest base image version (and therefore latest QPyLib). Using `"image": "qradar-app-base:2.0.0"` in your app manifest is fine, at the minute QRadar will make sure that if there's a later version of the base image to use it will use that, alongside the latest version of QPyLib. One thing to note is that this automatic upgrade is subject to change and is being discussed, but it should not affect app developers much.

**Comment by Skyw3lker** [comment]
This is causing my apps to stop on the new QRadar versions >=7.5. and **NO** documentation yet. at least there should be something soooon !!!!!!
