### ISSUE TITLE
to_json_dict question

### ISSUE THREAD

**Issue by FrankEargle** [IBM/qpylib#52]
Using to_json_dict QRadar 7.4.3, I have a dictionary like this:
[{'group': 'DMZ', 'name': 'External', 'cidr': '0.0.0.2/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'DMZ', 'name': 'Internal', 'cidr': '0.0.0.1/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'DMZ-DOM', 'name': 'dummyny', 'cidr': '127.127.0.1/32', 'description': '', 'domain': 'dummydom', 'location': '', 'country_code': 'US'}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '9.9.9.9/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '2222:aaaa:efc0:4a:68f8:b525:6666:aaaa/128', 'description': 'Default Network', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Core', 'cidr': '192.168.1.0/24', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'IOT', 'cidr': '192.168.3.0/24', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Net_10_0_0_0', 'cidr': '10.0.0.0/8', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Net_172_16_0_0', 'cidr': '172.16.0.0/12', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Net_192_168_0_0', 'cidr': '192.168.0.0/16', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '192.168.4.0/24', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '2222:fb90:5295:41de:21b:21ff:ffff:6666/128', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Net-10-172-192', 'name': 'v6', 'cidr': '2222:6080:b800:be69:4637:e6ff:ffff:5555/128', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Proxy_Servers', 'name': 'Proxy_Servers', 'cidr': '192.168.1.1/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Regulatory_Compliance_Servers', 'name': 'Regulatory_Compliance_Servers', 'cidr': '0.0.0.12/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Server_Network', 'name': 'Server_Network', 'cidr': '0.0.0.7/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.5/32', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.10/32', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.15/32', 'description': '', 'domain': 'Default Domain', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US'}, {'group': 'VPN_Addresses_Space', 'name': 'VPN_Addresses_Space', 'cidr': '0.0.0.3/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'VoIP_Networks', 'name': 'VoIP_Networks', 'cidr': '0.0.0.11/32', 'description': 'Default Network', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}, {'group': 'Wireless_Networks', 'name': 'all', 'cidr': '0.0.0.14/32', 'description': '', 'domain': 'Default Domain', 'location': '', 'country_code': 'US'}]

Once I call to_json_dict it looks like this:
[{'group': 'DMZ', 'name': 'External', 'cidr': '0.0.0.2/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'DMZ', 'name': 'Internal', 'cidr': '0.0.0.1/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'DMZ-DOM', 'name': 'dummyny', 'cidr': '127.127.0.1/32', 'description': '', 'location': '', 'country_code': 'US', 'domain_id': 1}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '9.9.9.9/32', 'description': 'Default Network', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '2222:aaaa:efc0:4a:68f8:b525:6666:aaaa/128', 'description': 'Default Network', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Core', 'cidr': '192.168.1.0/24', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'IOT', 'cidr': '192.168.3.0/24', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Net_10_0_0_0', 'cidr': '10.0.0.0/8', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Net_172_16_0_0', 'cidr': '172.16.0.0/12', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Net_192_168_0_0', 'cidr': '192.168.0.0/16', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '192.168.4.0/24', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '2222:fb90:5295:41de:21b:21ff:ffff:6666/128', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Net-10-172-192', 'name': 'v6', 'cidr': '2222:6080:b800:be69:4637:e6ff:ffff:5555/128', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Proxy_Servers', 'name': 'Proxy_Servers', 'cidr': '192.168.1.1/32', 'description': 'Default Network', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Regulatory_Compliance_Servers', 'name': 'Regulatory_Compliance_Servers', 'cidr': '0.0.0.12/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Server_Network', 'name': 'Server_Network', 'cidr': '0.0.0.7/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.5/32', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.10/32', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.15/32', 'description': '', 'location': "{'coordinates': [-80.00000, 30.00000], 'type': 'Point'}", 'country_code': 'US', 'domain_id': 0}, {'group': 'VPN_Addresses_Space', 'name': 'VPN_Addresses_Space', 'cidr': '0.0.0.3/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'VoIP_Networks', 'name': 'VoIP_Networks', 'cidr': '0.0.0.11/32', 'description': 'Default Network', 'location': '', 'country_code': 'US', 'domain_id': 0}, {'group': 'Wireless_Networks', 'name': 'all', 'cidr': '0.0.0.14/32', 'description': '', 'location': '', 'country_code': 'US', 'domain_id': 0}]

Neither the to_json_dict nor json.dumps output for the dictionary is accepted by the QRadar network Heirarchy API.  

[NOT:0000003000] An invalid parameter was passed to the API call; error message: {'http_response': {'code': 422, 'message': 'The request was well-formed but was unable to be followed due to semantic errors'}, 'code': 11, 'description': '', 'details': {}, 'message': 'Failed to transform user request body with a content type of "APPLICATION_JSON"'}; HTTPError('422 Client Error: 422 for url: https://qradar/api/config/network_hierarchy/staged_networks',)

Several articles or python helps on the web mention that JSON requires double quotes, not single.  When I use the API manually the json returned there has double quotes.  Does that matter?

**Comment by mbengit** [comment]
The dictionary value you posted isn't valid JSON. Try pasting it into a formatter, e.g. https://jsonformatter.org/json-parser

**Comment by FrankEargle** [comment]
The first blob was supposed to be the raw python dictionary.  Sorry, below is the dictionary.  The to_json_dict results are the second blob above.

['GROUP', 'NAME', 'CIDR', 'DESCRIPTION', 'DOMAIN', 'LOCATION', 'COUNTRY_CODE']; data: [{'group': 'DMZ', 'name': 'External', 'cidr': '0.0.0.2/32', 'description': 'Default Network', 'id': 53, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'DMZ', 'name': 'Internal', 'cidr': '0.0.0.1/32', 'description': 'Default Network', 'id': 54, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'DMZ-DOM', 'name': 'dummyny', 'cidr': '127.127.0.1/32', 'description': '', 'id': 104, 'country_code': 'US', 'domain': 'dummydom'}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '9.9.9.9/32', 'description': 'Default Network', 'id': 96, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'NAT_Ranges', 'name': 'NAT_Ranges', 'cidr': '2666:a000:efc0:4a:68f8:b525:6666:aa28/128', 'description': 'Default Network', 'id': 97, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Core', 'cidr': '192.168.1.0/24', 'description': '', 'id': 90, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'IOT', 'cidr': '192.168.2.0/24', 'description': '', 'id': 92, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Net_10_0_0_0', 'cidr': '10.0.0.0/8', 'description': 'Default Network', 'id': 59, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Net_172_16_0_0', 'cidr': '172.16.0.0/12', 'description': 'Default Network', 'id': 60, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Net_192_168_0_0', 'cidr': '192.168.0.0/16', 'description': 'Default Network', 'id': 61, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '192.168.3.0/24', 'description': '', 'id': 107, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'Tmobile', 'cidr': '2222:fb90:5295:41de:21b:21ff:fe86:6666/128', 'description': '', 'id': 108, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Net-10-172-192', 'name': 'v6', 'cidr': '2222:6080:b800:be69:4637:e6ff:ffff:5555/128', 'description': '', 'id': 94, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Proxy_Servers', 'name': 'Proxy_Servers', 'cidr': '192.168.1.1/32', 'description': 'Default Network', 'id': 98, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Regulatory_Compliance_Servers', 'name': 'Regulatory_Compliance_Servers', 'cidr': '0.0.0.12/32', 'description': 'Default Network', 'id': 63, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Server_Network', 'name': 'Server_Network', 'cidr': '0.0.0.7/32', 'description': 'Default Network', 'id': 64, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.5/32', 'description': '', 'id': 99, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.10/32', 'description': '', 'id': 100, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Server_Network', 'name': 'Servers', 'cidr': '192.168.1.15/32', 'description': '', 'id': 101, 'location': {'coordinates': [-80.00000, 30.00000], 'type': 'Point'}, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'VPN_Addresses_Space', 'name': 'VPN_Addresses_Space', 'cidr': '0.0.0.3/32', 'description': 'Default Network', 'id': 68, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'VoIP_Networks', 'name': 'VoIP_Networks', 'cidr': '0.0.0.11/32', 'description': 'Default Network', 'id': 69, 'country_code': 'US', 'domain': 'Default Domain'}, {'group': 'Wireless_Networks', 'name': 'all', 'cidr': '0.0.0.14/32', 'description': '', 'id': 70, 'country_code': 'US', 'domain': 'Default Domain'}]
